// src/popup/Popup.vue
<template>
<div class="switch-container-wrap" @mouseenter="activeContainer" @mouseleave="hideContainer">
  <div class="switch-container">
    <div class="active-switch">
      <span class="switch-title">{{ $t('app_temp_active_title') }}</span>
      <input type="checkbox" id="opt-temp-active" class="btn-switch" v-model="tempOff" @click.prevent="changeTempOff" @focus="activeContainer">
      <label for="opt-temp-active"></label>
    </div>
    <div class="active-switch">
      <span class="switch-title">{{ $t('instant_capture_title') + (insCapMode === 'pinMode' ? $t('instant_capture_pinned') : '') }}</span>
      <input type="checkbox" id="opt-instant-capture" class="btn-switch" v-model="config[insCapMode].instant.enable" @click.prevent="changeInsCap" @focus="activeContainer">
      <label for="opt-instant-capture"></label>
    </div>
    <div class="active-switch">
      <svg class="icon-qrcode" @mouseenter="showQRcode" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 612 612">
        <path d="M0 225v25h250v-25H0zM0 25h250V0H0v25z"/>
        <path d="M0 250h25V0H0v250zm225 0h25V0h-25v250zM87.5 162.5h75v-75h-75v75zM362 587v25h80v-25h-80zm0-200h80v-25h-80v25z"/>
        <path d="M362 612h25V362h-25v250zm190-250v25h60v-25h-60zm-77.5 87.5v25h50v-25h-50z"/>
        <path d="M432 497.958v-25h-70v25h70zM474.5 387h50v-25h-50v25zM362 225v25h250v-25H362zm0-200h250V0H362v25z"/>
        <path d="M362 250h25V0h-25v250zm225 0h25V0h-25v250zm-137.5-87.5h75v-75h-75v75zM0 587v25h250v-25H0zm0-200h250v-25H0v25z"/>
        <path d="M0 612h25V362H0v250zm225 0h25V362h-25v250zM87.5 524.5h75v-75h-75v75zM587 612h25V441h-25v171zM474.5 499.5v25h50v-25h-50z"/>
        <path d="M474.5 449.5v75h25v-75h-25zM562 587v25h50v-25h-50z"/>
      </svg>
      <span class="switch-title">{{ $t('app_active_title') }}</span>
      <input type="checkbox" id="opt-active" class="btn-switch" :checked="config.active" @click.prevent="changeActive" @focus="activeContainer">
      <label for="opt-active"></label>
    </div>
  </div>
  <transition name="fade">
    <div class="qrcode-panel" v-if="currentTabUrl" @mouseleave="currentTabUrl = ''">
      <qriously :value="currentTabUrl" :size="250" />
      <p class="qrcode-panel-title">{{ $t('qrcode_title') }}</p>
    </div>
  </transition>
  <transition name="fade">
    <div class="page-no-response-panel" v-if="showPageNoResponse">
      <p class="page-no-response-title">{{ $t('page_no_response') }}</p>
    </div>
  </transition>
</div>
</template>

<script lang="ts">
import Vue from 'vue'
import { message, storage } from '@/_helpers/browser-api'
import { MsgType, MsgTempDisabledState, MsgIsPinned, MsgQueryPanelState } from '@/typings/message'
import { appConfigFactory, AppConfigMutable } from '@/app-config'
import { createActiveConfigStream, updateActiveConfig } from '@/_helpers/config-manager'

export default Vue.extend({
  name: 'Popup',
  data () {
    return {
      config: appConfigFactory() as AppConfigMutable,
      currentTabUrl: '',
      tempOff: false,
      showPageNoResponse: false,
      insCapMode: 'mode' as 'mode' | 'pinMode',
    }
  },
  watch: {
    showPageNoResponse (val) {
      if (val) {
        clearTimeout(this['__pageNoResponseTimeout'])
        this['__pageNoResponseTimeout'] = setTimeout(() => {
          this.showPageNoResponse = false
        }, 2000)
      }
    }
  },
  methods: {
    changeActive () {
      this.config.active = !this.config.active
      updateActiveConfig(this.config)
    },
    changeTempOff () {
      const newTempOff = !this.tempOff

      browser.tabs.query({ active: true, currentWindow: true })
        .then(tabs => {
          if (tabs.length > 0 && tabs[0].id != null) {
            return message.send<MsgTempDisabledState>(
              tabs[0].id as number,
              {
                type: MsgType.TempDisabledState,
                op: 'set',
                value: newTempOff,
              },
            )
          }
        })
        .then(isSuccess => {
          if (isSuccess) {
            this.tempOff = newTempOff
          } else {
            return Promise.reject(new Error('Set tempOff failed')) as Promise<any>
          }
        })
        .catch(() => this.showPageNoResponse = true)
    },
    changeInsCap () {
      this.config[this.insCapMode].instant.enable = !this.config[this.insCapMode].instant.enable
      updateActiveConfig(this.config)
    },
    showQRcode () {
      chrome.tabs.query({active: true, currentWindow: true}, tabs => {
        if (tabs.length > 0 && tabs[0].url) {
          this.currentTabUrl = tabs[0].url as string
        }
      })
    },
    activeContainer () {
      const $frameRoot = document.querySelector<HTMLDivElement>('#frame-root')
      const $container = document.querySelector<HTMLDivElement>('.switch-container-wrap')
      if ($frameRoot && $container) {
        $frameRoot.style.height = '400px'
        $container.style.height = '150px'
      }
    },
    hideContainer () {
      const $frameRoot = document.querySelector<HTMLDivElement>('#frame-root')
      const $container = document.querySelector<HTMLDivElement>('.switch-container-wrap')
      if ($frameRoot && $container) {
        $frameRoot.style.height = '500px'
        $container.style.height = '50px'
        this.currentTabUrl = ''
      }
    },
  },
  created () {
    createActiveConfigStream().subscribe(config => {
      this.config = config as AppConfigMutable
    })

    browser.tabs.query({ active: true, currentWindow: true })
      .then(tabs => {
        if (tabs.length > 0 && tabs[0].id != null) {
          message.send<MsgTempDisabledState>(
            tabs[0].id as number,
            {
              type: MsgType.TempDisabledState,
              op: 'get',
            },
          ).then(flag => {
            this.tempOff = flag
          })

          message.send<MsgQueryPanelState, boolean>(
            tabs[0].id as number,
            {
              type: MsgType.QueryPanelState,
              path: 'widget.isPinned',
            },
          ).then(isPinned => {
            this.insCapMode = isPinned ? 'pinMode' : 'mode'
          })
        }
      })
      .catch(err => console.warn('Error when receiving MsgTempDisabled response', err))
  },
})
</script>

<style lang="scss">
/*------------------------------------*\
   Base
\*------------------------------------*/
html {
  margin: 0;
  padding: 0;
  overflow: hidden;
}

body {
  width: 450px;
  height: 550px;
  margin: 0;
  padding: 0;
  overflow: hidden;
  font-size: 14px;
  font-family: "Helvetica Neue", Helvetica, Arial, "Hiragino Sans GB", "Hiragino Sans GB W3", "Microsoft YaHei UI", "Microsoft YaHei", "WenQuanYi Micro Hei", sans-serif;
}

#frame-root {
  height: 500px;
  transition: height 0.5s;

  // hide white spaces
  font-size: 0;
}

.saladict-DIV {
  height: 100%;
}

.saladict-DictPanel {
  position: static;
  overflow: hidden;
  height: 100%;
  transition: height 0.5s;
}

.qrcode-panel {
  position: fixed;
  z-index: 100;
  bottom: 10px;
  left: 10px;
  padding: 10px;
  background: #fff;
  border-radius: 10px;
  box-shadow: rgba(0, 0, 0, 0.8) 0px 4px 23px -6px;
}

.qrcode-panel-title {
  text-align: center;
  margin: 5px 0 0 0;
}

.page-no-response-panel {
  position: fixed;
  z-index: 100;
  bottom: 60px;
  right: 25px;
  padding: 0 10px;
  background: #fff;
  border-radius: 10px;
  box-shadow: rgba(0, 0, 0, 0.8) 0px 4px 23px -6px;
}

.switch-container-wrap {
  position: relative;
  overflow: hidden;
  height: 50px;
  transition: height 0.5s;

  &::before {
    content: '';
    display: block;
    position: relative;
    z-index: 100;
    height: 10px;
    box-shadow: inset 0 10px 6px -6px rgba(0,0,0,.13);
    pointer-events: none;
  }
}

.switch-container {
  position: absolute;
  bottom: 0;
  width: 100%;
  overflow: hidden;
  background: #f9f9f9;
}

.active-switch {
  display: flex;
  align-items: center;
  position: relative;
  height: 49px;
  border-bottom: 1px solid #d8d8d8;
  padding: 0 20px;
  user-select: none;

  &:last-child {
    border-bottom-color: transparent;
  }
}

.icon-qrcode {
  width: 20px;
  margin-top: 3px;
}

.switch-title {
  flex: 1;
  font-size: 1.2em;
  padding: 0 15px;
  text-align: left;
  color: #333;
}

$switch-button-width: 55px;
$switch-button-height: 35px;
.btn-switch {
  // hide input
  position: absolute;
  z-index: -200000;
  opacity: 0;

  & + label {
    display: inline-block;
    width: $switch-button-width;
    height: $switch-button-height;
    position: relative;
    margin: auto;
    background-color: #ddd;
    border-radius: $switch-button-height;
    cursor: pointer;
    outline: 0;
    user-select: none;
  }

  & + label:before {
    content: '';
    display: block;
    position: absolute;
    top: 1px;
    left: 1px;
    bottom: 1px;
    right: 1px;
    background-color: #f1f1f1;
    border-radius: $switch-button-height;
    transition: background 0.4s;
  }

  & + label:after {
    content: '';
    display: block;
    position: absolute;
    height: $switch-button-height - 2px;
    width: $switch-button-height - 2px;
    background-color: #fff;
    border-radius: 100%;
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
    transition: margin 0.4s;
  }

  &:checked + label:before {
    background-color: #8ce196;
  }

  &:checked + label:after {
    margin-left: $switch-button-width - $switch-button-height + 2px;
  }

  &:active + label,
  &:focus + label {
    outline: 5px auto rgb(59, 153, 252);
    outline: 5px auto -webkit-focus-ring-color;
  }

  & + label:hover {
    outline: none !important;
  }
}

.fade-enter-active, .fade-leave-active {
  transition: opacity .5s
}
.fade-enter, .fade-leave-active {
  opacity: 0
}
</style>

// src/popup/Popup.tsx
import React from 'react'
import QRCode from 'qrcode.react'
import CSSTransition from 'react-transition-group/CSSTransition'
import { translate } from 'react-i18next'
import { TranslationFunction } from 'i18next'
import { message } from '@/_helpers/browser-api'
import { appConfigFactory, AppConfig } from '@/app-config'
import { createActiveConfigStream, updateActiveConfig } from '@/_helpers/config-manager'
import {
  MsgType,
  MsgQueryPanelState,
  MsgTempDisabledState,
} from '@/typings/message'

interface PopupState {
  config: AppConfig
  currentTabUrl: string
  isShowUrlBox: boolean
  tempOff: boolean
  showPageNoResponse: boolean
  insCapMode: 'mode' | 'pinMode'
}

export class Popup extends React.Component<{ t: TranslationFunction }, PopupState> {
  state = {
    config: appConfigFactory(),
    currentTabUrl: '',
    isShowUrlBox: false,
    tempOff: false,
    showPageNoResponse: false,
    insCapMode: 'mode' as 'mode' | 'pinMode',
  }

  constructor (props: any) {
    super(props)
    createActiveConfigStream().subscribe(config => {
      this.setState({ config })
    })

    browser.tabs.query({ active: true, currentWindow: true })
      .then(tabs => {
        if (tabs.length > 0 && tabs[0].id != null) {
          message.send<MsgTempDisabledState>(
            tabs[0].id as number,
            {
              type: MsgType.TempDisabledState,
              op: 'get',
            },
          ).then(flag => {
            this.setState({ tempOff: flag })
          })

          message.send<MsgQueryPanelState, boolean>(
            tabs[0].id as number,
            {
              type: MsgType.QueryPanelState,
              path: 'widget.isPinned',
            },
          ).then(isPinned => {
            this.setState({ insCapMode: isPinned ? 'pinMode' : 'mode' })
          })
        }
      })
      .catch(err => console.warn('Error when receiving MsgTempDisabled response', err))
  }

  activeContainer = () => {
    const $frameRoot = document.querySelector<HTMLDivElement>('#frame-root')
    const $container = document.querySelector<HTMLDivElement>('.switch-container-wrap')
    if ($frameRoot && $container) {
      $frameRoot.style.height = '400px'
      $container.style.height = '150px'
    }
  }

  hideContainer = () => {
    const $frameRoot = document.querySelector<HTMLDivElement>('#frame-root')
    const $container = document.querySelector<HTMLDivElement>('.switch-container-wrap')
    if ($frameRoot && $container) {
      $frameRoot.style.height = '500px'
      $container.style.height = '50px'
      this.setState({ currentTabUrl: '' })
    }
  }

  changeTempOff = () => {
    const oldTempOff = this.state.tempOff
    const newTempOff = !oldTempOff

    this.setState({ tempOff: newTempOff })

    browser.tabs.query({ active: true, currentWindow: true })
      .then(tabs => {
        if (tabs.length > 0 && tabs[0].id != null) {
          return message.send<MsgTempDisabledState>(
            tabs[0].id as number,
            {
              type: MsgType.TempDisabledState,
              op: 'set',
              value: newTempOff,
            },
          )
        }
      })
      .then(isSuccess => {
        if (!isSuccess) {
          this.setState({ tempOff: oldTempOff })
          return Promise.reject(new Error('Set tempOff failed')) as Promise<any>
        }
      })
      .catch(() => this.setState({ showPageNoResponse: true }))
  }

  changeInsCap = () => {
    const { config, insCapMode } = this.state
    const newConfig: AppConfig = {
      ...config,
      [insCapMode]: {
        ...config[insCapMode],
        instant: {
          ...config[insCapMode].instant,
          enable: !config[insCapMode].instant.enable
        }
      }
    }
    this.setState({ config: newConfig })
    updateActiveConfig(newConfig)
  }

  showQRcode = () => {
    chrome.tabs.query({ active: true, currentWindow: true }, tabs => {
      if (tabs.length > 0) {
        const url = tabs[0].url
        if (url) {
          if (!url.startsWith('http')) {
            const match = /static\/pdf\/web\/viewer\.html\?file=(.*)$/.exec(url)
            if (match) {
              this.setState({
                isShowUrlBox: true,
                currentTabUrl: decodeURIComponent(match[1]),
              })
              return
            }
          }
          this.setState({
            isShowUrlBox: false,
            currentTabUrl: url,
          })
        }
      }
    })
  }

  changeActive = () => {
    const { config } = this.state
    const newConfig = {
      ...config,
      active: !config.active
    }
    this.setState({ config: newConfig })
    updateActiveConfig(newConfig)
  }

  clearCurrentTabUrl = () => {
    this.setState({ currentTabUrl: '' })
  }

  renderQRPanel = () => {
    const { t } = this.props
    const {
      isShowUrlBox,
      currentTabUrl,
      showPageNoResponse,
    } = this.state
    return (
      <div className='qrcode-panel' onMouseLeave={this.clearCurrentTabUrl}>
        <QRCode value={currentTabUrl} size={250} />
        <p className='qrcode-panel-title'>
          {isShowUrlBox
            ? <input
                type='text'
                autoFocus
                readOnly
                value={currentTabUrl}
                onFocus={e => e.currentTarget.select()}
              />
            : <span>{t('qrcode_title')}</span>
          }
        </p>
        {showPageNoResponse &&
          <div className='page-no-response-panel'>
            <p className='page-no-response-title'>{t('page_no_response')}</p>
          </div>
        }
      </div>
    )
  }

  render () {
    const { t } = this.props
    const {
      config,
      currentTabUrl,
      tempOff,
      insCapMode,
    } = this.state

    return (
      <div
        className='switch-container-wrap'
        onMouseEnter={this.activeContainer}
        onMouseLeave={this.hideContainer}
      >
        <div className='switch-container'>
          <div className='active-switch'>
            <span className='switch-title'>{t('app_temp_active_title')}</span>
            <input
              type='checkbox'
              id='opt-temp-active'
              className='btn-switch'
              checked={tempOff}
              onClick={this.changeTempOff}
              onFocus={this.activeContainer}
            />
            <label htmlFor='opt-temp-active'></label>
          </div>
          <div className='active-switch'>
            <span className='switch-title'>{
              t('instant_capture_title') +
              (insCapMode === 'pinMode' ? t('instant_capture_pinned') : '')
            }</span>
            <input
              type='checkbox'
              id='opt-instant-capture'
              className='btn-switch'
              checked={config[insCapMode].instant.enable}
              onClick={this.changeInsCap}
              onFocus={this.activeContainer}
            />
            <label htmlFor='opt-instant-capture'></label>
          </div>
          <div className='active-switch'>
            <svg
              className='icon-qrcode'
              onMouseEnter={this.showQRcode}
              xmlns='http://www.w3.org/2000/svg'
              viewBox='0 0 612 612'
            >
              <path d='M0 225v25h250v-25H0zM0 25h250V0H0v25z'/>
              <path d='M0 250h25V0H0v250zm225 0h25V0h-25v250zM87.5 162.5h75v-75h-75v75zM362 587v25h80v-25h-80zm0-200h80v-25h-80v25z'/>
              <path d='M362 612h25V362h-25v250zm190-250v25h60v-25h-60zm-77.5 87.5v25h50v-25h-50z'/>
              <path d='M432 497.958v-25h-70v25h70zM474.5 387h50v-25h-50v25zM362 225v25h250v-25H362zm0-200h250V0H362v25z'/>
              <path d='M362 250h25V0h-25v250zm225 0h25V0h-25v250zm-137.5-87.5h75v-75h-75v75zM0 587v25h250v-25H0zm0-200h250v-25H0v25z'/>
              <path d='M0 612h25V362H0v250zm225 0h25V362h-25v250zM87.5 524.5h75v-75h-75v75zM587 612h25V441h-25v171zM474.5 499.5v25h50v-25h-50z'/>
              <path d='M474.5 449.5v75h25v-75h-25zM562 587v25h50v-25h-50z'/>
            </svg>
            <span className='switch-title'>{t('app_active_title')}</span>
            <input
              type='checkbox'
              id='opt-active'
              className='btn-switch'
              checked={config.active}
              onClick={this.changeActive}
              onFocus={this.activeContainer}
            />
            <label htmlFor='opt-active'></label>
          </div>
        </div>
        <CSSTransition
          classNames='fade'
          in={!!currentTabUrl}
          appear
          timeout={500}
          exit={false}
          mountOnEnter
          unmountOnExit
        >{this.renderQRPanel}</CSSTransition>
      </div>
    )
  }
}

export default translate()(Popup)
